/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* DESIGN.md token mappings */
        'ds-red': '#e60012',
        'ds-signal': '#f68d1f',
        'ds-amber': '#ecab37',
        'ds-nav-gold': '#e48600',
        'ds-canvas': '#7a8aba',
        'ds-canvas-soft': '#9fbee7',
        'ds-sky': '#9fbee7',
        'ds-lavender': '#acace7',
        'ds-ice': '#c0d5e6',
        'ds-periwinkle': '#8ba1d4',
        'ds-chrome-indigo': '#3d4f97',
        'ds-muted-indigo': '#60619c',
        'ds-platinum': '#dedede',
        'ds-surface': '#ffffff',
        'ds-carbon': '#21242e',
        'ds-hairline': '#5a5f8c',
        'ds-ink': '#21242e',
        'ds-ink-soft': '#3d4f97',
        'ds-on-primary': '#ffffff',
        'ds-error': '#e60012',
        'ds-systems-teal': '#206479',
        'ds-games-red': '#a7282b',
      },
      fontFamily: {
        display: ['Arial Black', 'Arial', 'sans-serif'],
        body: ['Arial', 'Helvetica', 'sans-serif'],
        mono: ['Arial', 'monospace'],
      },
      fontSize: {
        'ds-display': ['44px', { lineHeight: '1', fontWeight: '900', letterSpacing: '0' }],
        'ds-hero': ['15px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0' }],
        'ds-nav': ['13px', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.5px' }],
        'ds-label': ['11px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '0.5px' }],
        'ds-body': ['12px', { lineHeight: '1.4', fontWeight: '400', letterSpacing: '0' }],
        'ds-link': ['12px', { lineHeight: '1.4', fontWeight: '700', letterSpacing: '0' }],
        'ds-micro': ['10px', { lineHeight: '1.3', fontWeight: '400', letterSpacing: '0' }],
      },
      spacing: {
        'ds-xxs': '2px',
        'ds-xs': '4px',
        'ds-sm': '8px',
        'ds-md': '12px',
        'ds-lg': '16px',
        'ds-xl': '24px',
        'ds-xxl': '32px',
        'ds-section': '48px',
      },
      borderRadius: {
        'ds-none': '0px',
        'ds-xs': '2px',
        'ds-sm': '4px',
        'ds-md': '6px',
        'ds-lg': '10px',
        'ds-full': '9999px',
      },
      boxShadow: {
        'ds-bevel-top': 'inset 0 1px 0 rgba(255,255,255,0.5)',
        'ds-bevel-bottom': 'inset 0 -2px 0 #3d4f97',
        'ds-carbon': '0 2px 4px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
}
